name: deploy-x86-snap

on:
  workflow_run:
    workflows:
      - build-x86-snap
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main'
    runs-on: [self-hosted, amd64-server-2]

    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

    steps:
      - name: deploy
        run: |
          snapcraft upload $(realpath /tmp/ci-artifacts-x86/wick_*.snap) --release edge
