name: build-arm64-snap

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: self-hosted

    steps:
      - name: checkout git repository
        uses: actions/checkout@v2

      - name: build snap
        run: snapcraft --use-lxd

      - name: copy build artifacts
        if: ${{ github.event_name == 'merged' && github.ref == 'refs/heads/main' }}
        run: |
          mkdir -p ~/ci-artifacts
          cp wick_*.snap ~/ci-artifacts/wick_arm64.snap
