name: build-x86-snap

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: [self-hosted, amd64-server-2]

    steps:
      - name: checkout git repository
        uses: actions/checkout@v2

      - name: build snap
        run: |
          snapcraft clean --use-lxd
          snapcraft --use-lxd

      - name: copy build artifacts
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          rm -rf /tmp/ci-artifacts-x86
          mkdir -p /tmp/ci-artifacts-x86
          cp $(realpath wick_*.snap) /tmp/ci-artifacts-x86
